### ISSUE TITLE
关于paper-index-callout的用法

### ISSUE THREAD

**Issue by Sleepleeps** [dmscode/Obsidian-Templates#2]
作者你好，我并不太会用github，只能找到这个入口。
我太喜欢你的一些用法了，感觉实用又漂亮，尤其喜欢paper-index-callout。
paper-index-callout真漂亮呀，我就是有点纳闷它的用法。
一般您是什么场合或者情况下会使用这个callout呢，十几个不同位置的callout索引有什么奇妙的用法嘛？

**Comment by dmscode** [comment]
说出来你可能会失望了，我不用，我甚至都忘记了这是什么，看到你的评论后，我翻找着看了代码，看了说明，才想起来。

当初我写这个是为了整理书签，浏览器里的书签，但是我想放到 Obsidian，那数量可能比较多，不方便阅读，有分组也不方便呀，就用这种形式，callouts 又可以折叠起来。

但是说来惭愧，这个事情到现在还没解决，然后一直躺在我的待办列表里。而且现在我想到了其他的处理方式。

有时候这些东西我就是想到了，就写出来，就丢出来，万一有人需要呢，然后自己却未必需要（捂脸

也不必为功能而特地创造需求，这样就本末倒置了呀~一切功能都应该是为解决自己的问题而生的。

你基本可以一直在小众软件论坛（ https;//meta.appinn.net/ ）找到我，如果捐赠过咖啡的话，在爱发电给我发一条私信还可以进（并没有什么用的）微信群

感谢你的喜欢，这真的会给我很多动力！因为没有任何反馈的时候，我会以为完全没有人用这些东西，甚至最近都有点想删掉这些仓库了

**Comment by Sleepleeps** [comment]
十分感谢！这两天我感觉用它来整理一些原始素材（如新闻）等讯息很好用！它们会像简报一样在我页面上，有点手账的味道。你说的小众软件论坛我甚至没听过（），但我感觉好像有点好玩呢

**Comment by dmscode** [comment]
来试试吧，气氛很好的社区哦~
